---
- name: Provision app with NodeJS 20 and start with npm
  hosts: web                   # Replace with your target node inventory group or specific host
  become: yes                  # Use sudo privileges

  tasks:
    - name: Install curl (required to add NodeSource repository)
      ansible.builtin.apt:
        update_cache: yes
        name: curl
        state: present

    - name: Add NodeSource repository for Node.js 20
      ansible.builtin.shell:
        curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -


    - name: Install Node.js 20
     ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Verify Node.js version
      ansible.builtin.command: node -v
      register: node_version

    - name: Print Node.js version
      ansible.builtin.debug:
        var: node_version.stdout

    - name: Clone the Git repository
      ansible.builtin.git:
        repo: 'https://github.com/PriyanSappal/tech264-sparta-app.git'
        dest: /home/ubuntu/repo                             # Destination path on the target node
        version: main                                           # Branch to clone (e.g., main or master)
        force: yes

    - name: Install packages based on package.json
      community.general.npm:
        path: /home/ubuntu/repo/app/

    - name: Start the app with npm
      ansible.builtin.shell: npm start
      args:
        chdir: /home/ubuntu/repo/app # Path to the 'app' folder on the target node
      tags: npm_start
      
